[versions]
androidx-core = "1.6.0"
appcompat = "1.3.1"
material = "1.4.0"
compose = "1.0.1"
lifecycle = "2.4.0"
activity = "1.3.1"
navigation = "2.4.0-beta02"
protobuf = "3.10.0"
datastore = "1.0.0"
dagger = "2.38.1"
hilt = "1.0.0"
workmanager = "2.7.1"
logcat = "0.1"
junit = "4.13.2"
androidx-test-junit = "1.1.3"
androidx-test-espresso = "3.4.0"

[libraries]
androidxCore-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-androidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt" }
hilt-workCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }
workmanager-runtimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }

junit = { module = "junit:junit", version.ref = "junit" }
androidxTest-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }